package org.monarchinitiative.splicing;

import de.charite.compbio.jannovar.data.ReferenceDictionary;
import de.charite.compbio.jannovar.reference.*;
import org.monarchinitiative.splicing.calculate.ScoredTranscriptModel;

import java.util.Arrays;
import java.util.Collections;

/**
 * @author <a href="mailto:daniel.danis@jax.org">Daniel Danis</a>
 * @version 0.0.1
 * @since 0.0
 */
public class TestingData {

    private static ReferenceDictionary RD = HG19RefDictBuilder.build();


    public static ScoredTranscriptModel singleExonScoredTranscriptModel() {
        return new ScoredTranscriptModel(getSingleExonTranscriptModel(), Collections.singletonList(Double.NaN), Collections.singletonList(Double.NaN));
    }


    public static ScoredTranscriptModel twoExonScoredTranscriptModel() {
        return new ScoredTranscriptModel(getTwoExonTranscriptModel(),
                Arrays.asList(10.33267367738815, Double.NaN),
                Arrays.asList(Double.NaN, 10.293715220799694));
    }


    public static ScoredTranscriptModel threeExonScoredTranscriptModel() {
        return new ScoredTranscriptModel(getThreeExonTranscriptModel(),
                Arrays.asList(4.898803136983307, 8.566571105600822, Double.NaN),
                Arrays.asList(Double.NaN, 10.44145682272866, 8.727129021978236));
    }


    /**
     * @return {@link TranscriptModel} representing <code>NM_005325.3</code> transcript of the <em>HIST1H1A</em>. This
     * gene consists of a <em>single</em> exon
     */
    public static TranscriptModel getSingleExonTranscriptModel() {
        TranscriptModelBuilder builder = new TranscriptModelBuilder();
        builder.setAccession("NM_005325.3");
        builder.setGeneSymbol("HIST1H1A");
        builder.setTXRegion(new GenomeInterval(RD, Strand.FWD, 6, 26017259, 26018040).withStrand(Strand.REV));
        builder.setCDSRegion(new GenomeInterval(RD, Strand.FWD, 6, 26017312, 26017960).withStrand(Strand.REV));
        builder.addExonRegion(new GenomeInterval(RD, Strand.FWD, 6, 26017259, 26018040).withStrand(Strand.REV));
        builder.setSequence("TAGGCTGCGTTGGGGCCTTTTTTTCGCATCCTGCTTCGTCAGGTTTATACCACTTTATTTGGTGTGCTGTGTTAGTCACCATGTCTGAAACAGTGCCTCCCGCCCCCGCCGCTTCTGCTGCTCCTGAGAAACCTTTAGCTGGCAAGAAGGCAAAGAAACCTGCTAAGGCTGCAGCAGCCTCCAAGAAAAAACCCGCTGGCCCTTCCGTGTCAGAGCTGATCGTGCAGGCTGCTTCCTCCTCTAAGGAGCGTGGTGGTGTGTCGTTGGCAGCTCTTAAAAAGGCGCTGGCGGCCGCAGGCTACGACGTGGAGAAGAACAACAGCCGCATTAAGCTGGGCATTAAGAGCCTGGTAAGCAAGGGAACGTTGGTGCAGACAAAGGGTACCGGAGCCTCGGGTTCCTTCAAGCTCAACAAGAAGGCGTCCTCCGTGGAAACCAAGCCCGGCGCCTCAAAGGTGGCTACAAAAACTAAGGCAACGGGTGCATCTAAAAAGCTCAAAAAGGCCACGGGGGCTAGCAAAAAGAGCGTCAAGACTCCGAAAAAGGCTAAAAAGCCTGCGGCAACAAGGAAATCCTCCAAGAATCCAAAAAAACCCAAAACTGTAAAGCCCAAGAAAGTAGCTAAAAGCCCTGCTAAAGCTAAGGCTGTAAAACCCAAGGCGGCCAAGGCTAGGGTGACGAAGCCAAAGACTGCCAAACCCAAGAAAGCGGCACCCAAGAAAAAGTAAATTCAGTTAGAAGTTTCTTCTAGTAACCCAACGGCTCTTTTAAGAGCCACCTA");
        builder.setGeneID("3024");
        builder.setStrand(Strand.REV);
        builder.setTranscriptSupportLevel(-1);
        return builder.build();
    }


    /**
     * @return {@link TranscriptModel} representing <code>NM_004004.5</code> transcript of the <em>GJB2</em>. This
     * gene consists of <em>two</em> exons
     */
    public static TranscriptModel getTwoExonTranscriptModel() {
        TranscriptModelBuilder builder = new TranscriptModelBuilder();
        builder.setAccession("NM_004004.5");
        builder.setGeneSymbol("GJB2");
        builder.setTXRegion(new GenomeInterval(RD, Strand.FWD, 13, 20761601, 20767114).withStrand(Strand.REV));
        builder.setCDSRegion(new GenomeInterval(RD, Strand.FWD, 13, 20763039, 20763720).withStrand(Strand.REV));
        // two exons
        builder.addExonRegion(new GenomeInterval(RD, Strand.FWD, 13, 20766921, 20767114).withStrand(Strand.REV));
        builder.addExonRegion(new GenomeInterval(RD, Strand.FWD, 13, 20761601, 20763742).withStrand(Strand.REV));

        builder.setSequence("GGGGTGCGGTTAAAAGGCGCCACGGCGGGAGACAGGTGTTGCGGCCCCGCAGCGCCCGCGCGCTCCTCTCCCCGACTCGGAGCCCCTCGGCGGCGCCCGGCCCAGGACCCGCCTAGGAGCGCAGGAGCCCCAGCGCAGAGACCCCAACGCCGAGACCCCCGCCCCGGCCCCGCCGCGCTTCCTCCCGACGCAGAGCAAACCGCCCAGAGTAGAAGATGGATTGGGGCACGCTGCAGACGATCCTGGGGGGTGTGAACAAACACTCCACCAGCATTGGAAAGATCTGGCTCACCGTCCTCTTCATTTTTCGCATTATGATCCTCGTTGTGGCTGCAAAGGAGGTGTGGGGAGATGAGCAGGCCGACTTTGTCTGCAACACCCTGCAGCCAGGCTGCAAGAACGTGTGCTACGATCACTACTTCCCCATCTCCCACATCCGGCTATGGGCCCTGCAGCTGATCTTCGTGTCCACGCCAGCGCTCCTAGTGGCCATGCACGTGGCCTACCGGAGACATGAGAAGAAGAGGAAGTTCATCAAGGGGGAGATAAAGAGTGAATTTAAGGACATCGAGGAGATCAAAACCCAGAAGGTCCGCATCGAAGGCTCCCTGTGGTGGACCTACACAAGCAGCATCTTCTTCCGGGTCATCTTCGAAGCCGCCTTCATGTACGTCTTCTATGTCATGTACGACGGCTTCTCCATGCAGCGGCTGGTGAAGTGCAACGCCTGGCCTTGTCCCAACACTGTGGACTGCTTTGTGTCCCGGCCCACGGAGAAGACTGTCTTCACAGTGTTCATGATTGCAGTGTCTGGAATTTGCATCCTGCTGAATGTCACTGAATTGTGTTATTTGCTAATTAGATATTGTTCTGGGAAGTCAAAAAAGCCAGTTTAACGCATTGCCCAGTTGTTAGATTAAGAAATAGACAGCATGAGAGGGATGAGGCAACCCGTGCTCAGCTGTCAAGGCTCAGTCGCTAGCATTTCCCAACACAAAGATTCTGACCTTAAATGCAACCATTTGAAACCCCTGTAGGCCTCAGGTGAAACTCCAGATGCCACAATGGAGCTCTGCTCCCCTAAAGCCTCAAAACAAAGGCCTAATTCTATGCCTGTCTTAATTTTCTTTCACTTAAGTTAGTTCCACTGAGACCCCAGGCTGTTAGGGGTTATTGGTGTAAGGTACTTTCATATTTTAAACAGAGGATATCGGCATTTGTTTCTTTCTCTGAGGACAAGAGAAAAAAGCCAGGTTCCACAGAGGACACAGAGAAGGTTTGGGTGTCCTCCTGGGGTTCTTTTTGCCAACTTTCCCCACGTTAAAGGTGAACATTGGTTCTTTCATTTGCTTTGGAAGTTTTAATCTCTAACAGTGGACAAAGTTACCAGTGCCTTAAACTCTGTTACACTTTTTGGAAGTGAAAACTTTGTAGTATGATAGGTTATTTTGATGTAAAGATGTTCTGGATACCATTATATGTTCCCCCTGTTTCAGAGGCTCAGATTGTAATATGTAAATGGTATGTCATTCGCTACTATGATTTAATTTGAAATATGGTCTTTTGGTTATGAATACTTTGCAGCACAGCTGAGAGGCTGTCTGTTGTATTCATTGTGGTCATAGCACCTAACAACATTGTAGCCTCAATCGAGTGAGACAGACTAGAAGTTCCTAGTGATGGCTTATGATAGCAAATGGCCTCATGTCAAATATTTAGATGTAATTTTGTGTAAGAAATACAGACTGGATGTACCACCAACTACTACCTGTAATGACAGGCCTGTCCAACACATCTCCCTTTTCCATGACTGTGGTAGCCAGCATCGGAAAGAACGCTGATTTAAAGAGGTCGCTTGGGAATTTTATTGACACAGTACCATTTAATGGGGAGGACAAAATGGGGCAGGGGAGGGAGAAGTTTCTGTCGTTAAAAACAGATTTGGAAAGACTGGACTCTAAAGTCTGTTGATTAAAGATGAGCTTTGTCTACTTCAAAAGTTTGTTTGCTTACCCCTTCAGCCTCCAATTTTTTAAGTGAAAATATAGCTAATAACATGTGAAAAGAATAGAAGCTAAGGTTTAGATAAATATTGAGCAGATCTATAGGAAGATTGAACCTGAATATTGCCATTATGCTTGACATGGTTTCCAAAAAATGGTACTCCACATATTTCAGTGAGGGTAAGTATTTTCCTGTTGTCAAGAATAGCATTGTAAAAGCATTTTGTAATAATAAAGAATAGCTTTAATGATATGCTTGTAACTAAAATAATTTTGTAATGTATCAAATACATTTAAAACATTAAAATATAATCTCTATAATAATTTAAAAAAAAAAAAAAAAA");
        builder.setGeneID("2706");
        builder.setStrand(Strand.REV);
        builder.setTranscriptSupportLevel(-1);
        return builder.build();
    }


    public static TranscriptModel getThreeExonTranscriptModel() {
        TranscriptModelBuilder builder = new TranscriptModelBuilder();
        builder.setAccession("NM_020192.3");
        builder.setGeneSymbol("YAE1");
        builder.setTXRegion(new GenomeInterval(RD, Strand.FWD, 7, 39606002, 39612480));
        builder.setCDSRegion(new GenomeInterval(RD, Strand.FWD, 7, 39606017, 39612305));
        // three exons
        builder.addExonRegion(new GenomeInterval(RD, Strand.FWD, 7, 39606002, 39606146));
        builder.addExonRegion(new GenomeInterval(RD, Strand.FWD, 7, 39610104, 39610226));
        builder.addExonRegion(new GenomeInterval(RD, Strand.FWD, 7, 39611875, 39612480));

        builder.setSequence("GTAATTGCCTCGGTGATGTCGTGGGTTCAAGCAGCCTCCTTGATCCAGGGCCCTGGAGACAAAGGGGACGTGTTTGACGAAGAAGCAGACGAGTCGCTCCTGGCGCAGCGGGAATGGCAGAGTAACATGCAAAGACGAGTCAAAGAAGGTTATAGAGATGGAATAGATGCTGGCAAAGCAGTTACTCTTCAACAGGGCTTCAATCAAGGTTATAAGAAAGGTGCAGAAGTCATTTTAAACTATGGACGACTCCGAGGAACATTGAGTGCTTTGCTCTCCTGGTGTCACCTTCATAATAATAATTCAACTTTGATCAATAAAATAAACAATCTTCTGGATGCAGTTGGCCAGTGTGAAGAGTATGTGCTCAAACATCTGAAATCAATCACTCCACCGTCCCATGTTGTAGATTTATTGGACTCCATTGAGGATATGGACCTTTGTCATGTAGTTCCAGCTGAGAAAAAGATTGATGAAGCTAAAGATGAAAGACTCTGTGAAAATAATGCTGAGTTTAACAAAAACTGTAGCAAGAGCCATAGTGGGATAGATTGTTCATATGTAGAATGTTGTAGAACACAGGAGCATGCACATTCAGAAAACCCAAGCCCCACATGGATTTTGGAACAGACAGCCAGTTTAGTTAAACAGCTGGGCCTATCAGTAGATGTATTACAACACCTCAAACAACTATAAAATTACCTTCCCTTTTCTAATGAAAATAATGTTCAGAACATTTGGTTTCCTAACAATCGAAATTTGTACTGGTTTCTGCATCAAACACCTCAACTGTAGGGTTACCCTTTATGGAAGTTTGAAATTAACACTATTGTCTTCAAAATTAACACTATTAAATGTAATATAAGCCTTTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
        builder.setGeneID("570002");
        builder.setStrand(Strand.FWD);
        builder.setTranscriptSupportLevel(-1);
        return builder.build();
    }


    /**
     * @return DNA sequence of region of the <em>HIST1H1A</em> gene on FWD strand (>chr6:26017260-26018040 in hg19)
     */
    public static String getHIST1H1ASeq() {
        return "TAGGTGGCTCTTAAAAGAGCCGTTGGGTTACTAGAAGAAACTTCTAACTGAATTTACTTT" +
                "TTCTTGGGTGCCGCTTTCTTGGGTTTGGCAGTCTTTGGCTTCGTCACCCTAGCCTTGGCC" +
                "GCCTTGGGTTTTACAGCCTTAGCTTTAGCAGGGCTTTTAGCTACTTTCTTGGGCTTTACA" +
                "GTTTTGGGTTTTTTTGGATTCTTGGAGGATTTCCTTGTTGCCGCAGGCTTTTTAGCCTTT" +
                "TTCGGAGTCTTGACGCTCTTTTTGCTAGCCCCCGTGGCCTTTTTGAGCTTTTTAGATGCA" +
                "CCCGTTGCCTTAGTTTTTGTAGCCACCTTTGAGGCGCCGGGCTTGGTTTCCACGGAGGAC" +
                "GCCTTCTTGTTGAGCTTGAAGGAACCCGAGGCTCCGGTACCCTTTGTCTGCACCAACGTT" +
                "CCCTTGCTTACCAGGCTCTTAATGCCCAGCTTAATGCGGCTGTTGTTCTTCTCCACGTCG" +
                "TAGCCTGCGGCCGCCAGCGCCTTTTTAAGAGCTGCCAACGACACACCACCACGCTCCTTA" +
                "GAGGAGGAAGCAGCCTGCACGATCAGCTCTGACACGGAAGGGCCAGCGGGTTTTTTCTTG" +
                "GAGGCTGCTGCAGCCTTAGCAGGTTTCTTTGCCTTCTTGCCAGCTAAAGGTTTCTCAGGA" +
                "GCAGCAGAAGCGGCGGGGGCGGGAGGCACTGTTTCAGACATGGTGACTAACACAGCACAC" +
                "CAAATAAAGTGGTATAAACCTGACGAAGCAGGATGCGAAAAAAAGGCCCCAACGCAGCCT" +
                "A";
    }


    /**
     * @return DNA sequence of region of the <em>GJB2</em> gene on FWD strand (>chr13:20761602-20767114 in hg19)
     */
    public static String GJB2Seq() {
        return "TTTTAAATTATTATAGAGATTATATTTTAATGTTTTAAATGTATTTGATACATTACAAAA" +
                "TTATTTTAGTTACAAGCATATCATTAAAGCTATTCTTTATTATTACAAAATGCTTTTACA" +
                "ATGCTATTCTTGACAACAGGAAAATACTTACCCTCACTGAAATATGTGGAGTACCATTTT" +
                "TTGGAAACCATGTCAAGCATAATGGCAATATTCAGGTTCAATCTTCCTATAGATCTGCTC" +
                "AATATTTATCTAAACCTTAGCTTCTATTCTTTTCACATGTTATTAGCTATATTTTCACTT" +
                "AAAAAATTGGAGGCTGAAGGGGTAAGCAAACAAACTTTTGAAGTAGACAAAGCTCATCTT" +
                "TAATCAACAGACTTTAGAGTCCAGTCTTTCCAAATCTGTTTTTAACGACAGAAACTTCTC" +
                "CCTCCCCTGCCCCATTTTGTCCTCCCCATTAAATGGTACTGTGTCAATAAAATTCCCAAG" +
                "CGACCTCTTTAAATCAGCGTTCTTTCCGATGCTGGCTACCACAGTCATGGAAAAGGGAGA" +
                "TGTGTTGGACAGGCCTGTCATTACAGGTAGTAGTTGGTGGTACATCCAGTCTGTATTTCT" +
                "TACACAAAATTACATCTAAATATTTGACATGAGGCCATTTGCTATCATAAGCCATCACTA" +
                "GGAACTTCTAGTCTGTCTCACTCGATTGAGGCTACAATGTTGTTAGGTGCTATGACCACA" +
                "ATGAATACAACAGACAGCCTCTCAGCTGTGCTGCAAAGTATTCATAACCAAAAGACCATA" +
                "TTTCAAATTAAATCATAGTAGCGAATGACATACCATTTACATATTACAATCTGAGCCTCT" +
                "GAAACAGGGGGAACATATAATGGTATCCAGAACATCTTTACATCAAAATAACCTATCATA" +
                "CTACAAAGTTTTCACTTCCAAAAAGTGTAACAGAGTTTAAGGCACTGGTAACTTTGTCCA" +
                "CTGTTAGAGATTAAAACTTCCAAAGCAAATGAAAGAACCAATGTTCACCTTTAACGTGGG" +
                "GAAAGTTGGCAAAAAGAACCCCAGGAGGACACCCAAACCTTCTCTGTGTCCTCTGTGGAA" +
                "CCTGGCTTTTTTCTCTTGTCCTCAGAGAAAGAAACAAATGCCGATATCCTCTGTTTAAAA" +
                "TATGAAAGTACCTTACACCAATAACCCCTAACAGCCTGGGGTCTCAGTGGAACTAACTTA" +
                "AGTGAAAGAAAATTAAGACAGGCATAGAATTAGGCCTTTGTTTTGAGGCTTTAGGGGAGC" +
                "AGAGCTCCATTGTGGCATCTGGAGTTTCACCTGAGGCCTACAGGGGTTTCAAATGGTTGC" +
                "ATTTAAGGTCAGAATCTTTGTGTTGGGAAATGCTAGCGACTGAGCCTTGACAGCTGAGCA" +
                "CGGGTTGCCTCATCCCTCTCATGCTGTCTATTTCTTAATCTAACAACTGGGCAATGCGTT" +
                "AAACTGGCTTTTTTGACTTCCCAGAACAATATCTAATTAGCAAATAACACAATTCAGTGA" +
                "CATTCAGCAGGATGCAAATTCCAGACACTGCAATCATGAACACTGTGAAGACAGTCTTCT" +
                "CCGTGGGCCGGGACACAAAGCAGTCCACAGTGTTGGGACAAGGCCAGGCGTTGCACTTCA" +
                "CCAGCCGCTGCATGGAGAAGCCGTCGTACATGACATAGAAGACGTACATGAAGGCGGCTT" +
                "CGAAGATGACCCGGAAGAAGATGCTGCTTGTGTAGGTCCACCACAGGGAGCCTTCGATGC" +
                "GGACCTTCTGGGTTTTGATCTCCTCGATGTCCTTAAATTCACTCTTTATCTCCCCCTTGA" +
                "TGAACTTCCTCTTCTTCTCATGTCTCCGGTAGGCCACGTGCATGGCCACTAGGAGCGCTG" +
                "GCGTGGACACGAAGATCAGCTGCAGGGCCCATAGCCGGATGTGGGAGATGGGGAAGTAGT" +
                "GATCGTAGCACACGTTCTTGCAGCCTGGCTGCAGGGTGTTGCAGACAAAGTCGGCCTGCT" +
                "CATCTCCCCACACCTCCTTTGCAGCCACAACGAGGATCATAATGCGAAAAATGAAGAGGA" +
                "CGGTGAGCCAGATCTTTCCAATGCTGGTGGAGTGTTTGTTCACACCCCCCAGGATCGTCT" +
                "GCAGCGTGCCCCAATCCATCTTCTACTCTGGGCGGTTTGCTCTGGAAAAGACGAATGCAC" +
                "ACAACACAGGAATCACTAGCTAGGACAGAACAGGGAGACTTCTCTGAGTCTGGGTAAGCA" +
                "AGCATGCTTAAATCTCTTCCTGAGCAAACACCAACTCTTACACAACCTCACCAAAACAGG" +
                "TGAAGACAGAACCAACTTAGTTTGTCATAGGATTAAATGTATAGTTCCCAAACCCTCTTG" +
                "AACGTGTTTTTAGGTGTTCTCTGATAAAAAGTAGCTTGTTCACCTGAGTAATTCACCCAA" +
                "TCTTTAAACACATCATAAAAATTTGCTGTGCTGGGGAGTGTCATAAAGTCCTCGTTAGCT" +
                "GAAAGGCACTCAGGGGTTCTGACCGTACCCCTGCATCCTCTGCAGAGCTTCCTTGGGTCT" +
                "TCCTGACTCTGCAGAAGTTACTCAGCGTTCAACAGCTGCATCCATTTGCAGTCTCAAGTT" +
                "TTGGCTGTACCACTGGGGCCGATACTAGCTTGGGCCAACCTTGCTCAAAGGCTGAGAGGC" +
                "CAAGTACAGGAGAACCGTGAGGATAAGATGTCTAGTCTCTCTGCTGAGCCACTTTCCTTA" +
                "ATGTCTTGAATGAATTTTCACAGACGTGGCATGTAGCAGTGAAACTGTTGTTACCAGTGG" +
                "TTAAGTTTACATTTGAGGCACCCCGAGTTAAAATTTTACAAAGGACCTTGCTTCCTCCTA" +
                "CGTGAAAGGAAGAGGTTAGGAATGCCCTCTTCATGGAGAAAAGCCACTGTGAGCACAGAC" +
                "TTTCGTGTAGGCTTTGTGGATGGCTTGGTGGCCTCACTGTCAGGCTGGCACTGATGGCTC" +
                "AGTTAGCATATCTGTTTTGATAAGTGCTGCAACAGTGCATTATAATTGTGGGCTGTGGTT" +
                "TTAATTTCAAAGTGTTTCTTAAAAGACACATTATTTTAAAATGACAGAAAATTCAACTCC" +
                "CTCGGTTACTGGCCCAGCTAAGCGACGTCACTGCATTGCAGTTCAGCGCTGAAGCTTGGG" +
                "AGAGTCCCACACTCCTTACTGCAAGCGGATGTGGAGAGGCCAGTGGATAATCTCCTGTGA" +
                "GCCCATGGCCTTCTTTTCATCCCAGGATGTGAATTGTCTTCACTGATTCATAGTTACACC" +
                "CTGCCTGCCACAACCAACGCTCTCCTAAACAAGATTCCACCCTCTCCACAATCCGGATGA" +
                "ATCATCTCTTTTCCACCCTTCAGAGCTGGTAGTGAATCCTCCTTCTTCTTTTTCTTAAAA" +
                "GCATCCTCCTCTCCTCATTTTAGGCAAGTTGCATCCCGTTTTCTGATGGACTCCAGAAGC" +
                "AGGCTCGTAGTGAATGTCTTTCATGACCCACAGTCGCTGCCACGGGGCACCAAGGTCAGG" +
                "CAGAAACCATCCAGTGCCACCTTGGTCAGAGGCTAACAGGAGAGAGGTGGCCACGAAAGT" +
                "TACATCAGATTGACATAGGCCTGTGAAACATTTAGCTTCACTGAGCTTGGGAAAGACAAC" +
                "ATCATTGGAAAAAACAATATTTTAGCCCAGGTTCAGCACTGACCCATTGATAATCCAGAC" +
                "TGGGAGGCCCTTAGGTGAGCTGGTTGTCCTGCTACAGCACCCACAGCTCAGGCCAGTCCC" +
                "GTCCCAACAGCAGAACCACCGAGGACAGCAACATTCCGATTTTAACAAAAGCATCTTATG" +
                "GAATTAGACATTCTTCATTGGCCCTCACTGAGTGGAAAACAGGATACTCCCCGAAGTAAA" +
                "CTCTCTCCTGGTTTACAACAATACACCTGGCCAAGAATATGGGGCTGCAGGAGGAGGGGT" +
                "TTATCCTTTGCCCTCTTCCACCTGCCAAACCCAGGTCATACACCCTTCTACAGACCTGTC" +
                "CAGTTACCATCAGCTGAGAAAAATACAGTTCCGAGAAACCCTATATTGTTATTTTATAAA" +
                "GCTTGAGTTGAAGCTACCTGTTTTAAAGATCCTTTTTCAGGAAGAGGAGTAAATTAAGAT" +
                "TTACTCCCCAATGGGCTAGGGGGTCATGGGTTAAGAGGGGCTCAGAAGCAGGACGAAGTT" +
                "GTTTTCAATATTCAAGTCAGAGGAGGAGCTGCCCTCCTGGCCTCCCGACCCTGGGCGGTT" +
                "ACATGCAGCTTCCTACCGGGCCCACGCCATCCTGCACCGCCTGGAGGGCTGCCAGAGGCC" +
                "AGCGGAGGAGTTGGTTCAGTTCCTTAGGGAAGACACTAGGTGAATCACCAGGATCCAGAA" +
                "AAGGCAAAAGGGACTCTTCACCCCTTAAATTTCTCCACCCTTAGGTGATGGGTGGTCGAC" +
                "CTTGCCTGGCTGTCCCCAGAGGGTTCCTCCACCCTTCTCACCAGTGTCTGAAATTGTGAC" +
                "CGACTGTGCACAGCAGTTTCGAAAGGGACTCTAAGGTCACATGGGGACACGGCCGTACCA" +
                "CGCTTCTCAAGGCAGTCCCAGGTGCATGGCCACGGAACCCAGCTCTCAGCAGCTGTTAGT" +
                "TAGGTGAGCGCTGTTCGGGCTGCCTTCCTCCTCCAGTGGGGCAGGATCGAGGCACTGATG" +
                "GAACCGTCCTGAGGACGCGGGTCTCAGCCGCACACCACCTCTTCGCGAACAAGGGTCCTA" +
                "AAAATTTTCCTTCTAGGCGGGGAGCACAGCCCGGAAACAGACCCTCGTGAAGTGTTTAGG" +
                "AAAAAGGGAAGCCACTGAAATCTTGGCCCCGGGGTAGGCCGGGATCGGCTGGCTCCGCGT" +
                "TAGTTCTAGGCAAACTCCGCCCAAATCTCTGCCCGGGGATTTTTCTGCAGAAGCCGCTCC" +
                "AAGAGGTAAAGGTCAGTTCCTGCAGCGAAGGCTTCCTGCTTCACCGGCGAAACGGAGCTT" +
                "TGCTTCGAAGCTAAGCTTTCGGTGAATTTAAAACGTTTGGTGGCAGTGGGTCAAGTAGCC" +
                "AGGCGGCTGCGCTAGAGTACCCCGAAGGGACATCGGCGACACCACAAACCTCGCGCTGGC" +
                "GGCTCGCCCGCGCCTTTTTCCCCTCCCGCGCGCGCCCGGCCCCACTCGCACCCCGGGCGG" +
                "TGCCATCGCGTCCACTTCCCCGGCCGCCCCATTCCAGCTCCGGAGCTCGGCCGCAGAAAC" +
                "GCCCGCTCCAGAAggcggcccccgccccccggcccAAGGACGTGTGTTGGTCCAGCCCCC" +
                "CGGTTCCCCGAGACCCACGCGGCCGGGCAACCGCTCTGGGTCTCGCGGTCCCTCCCCGCG" +
                "CCAGGTTCCTGGCCGGGCAGTCCGGGGCCGGCGGGCTCACCTGCGTCGGGAGGAAgcgcg" +
                "gcggggccggggcgggggTCTCGGCGTTGGGGTCTCTGCGCTGGGGCTCCTGCGCTCCTA" +
                "GGCGGGTCCTGGGCCGGGCGCCGCCGAGGGGCTCCGAGTCGGGGAGAGGAGCGCGCGGGC" +
                "GCTGCGGGGCCGCAACACCTGTCTCCCGCCGTGGCGCCTTTTAACCGCACCCC";
    }


    /**
     * @return DNA sequence of region of the <em>YAE1</em> gene on FWD strand (>chr7:39606003-39612480 in hg19)
     */
    public static String getYAE1Seq() {
        return "GTAATTGCCTCGGTGATGTCGTGGGTTCAAGCAGCCTCCTTGATCCAGGGCCCTGGAGAC" +
                "AAAGGGGACGTGTTTGACGAAGAAGCAGACGAGTCGCTCCTGGCGCAGCGGGAATGGCAG" +
                "AGTAACATGCAAAGACGAGTCAAAGTAAACGTGGTGTGGACGGCGCGGGGTGCTGGGTTG" +
                "TGGGAAGAGGCGCGGAGTTGTGAAGAAGCTGGGTCCAGAGTGGCCCCAGCCTGGCCCGGC" +
                "GCTGCTCTCTTTATCCCTAGGGACCCGGTCCGACCCGCGTCTTGCTAGGATTTCTCGATG" +
                "GTTACTTGAAAGCGTGTAAAACAACAAGACGCATTCTTTGAGCGCCTACGGGATGCGTTA" +
                "GAAACTGAGGACCGACCAAAATTAACTATGTGTAGACTTTGAACAGTTTGCAGTTTGTTG" +
                "AGGATCACAGGGAAAGGAGCTGGAGAGAAACATACACTATACTTATTATGGCTGTCAAAG" +
                "GACGTGTACGCAGTTTATATGGGTGGCTTGAATGGGTAGGGAGCCTAAAGTTAAGGAGTA" +
                "GTGTTAATCAAGACATATTGAAAAGATGAACTAAAGCATGCTGTCAGAGGACAATAAGGG" +
                "AAAGCTAATGTGGAATACTGGTGTCTAGGTAAGGGAATATTAAAGTTGGTTTCTTTTTTA" +
                "TTTGTTAGATGTAACTTTTTCATCTCTAATTTGTCTCACTATTCATTGAAACTAAGCTTA" +
                "ATTTCTGTGTGCAGCCTACAGTATTTCTGGGTGAGGACCAAATAGTGAGGTCCACATCCA" +
                "CTTAATATATTTGCCAACCATTAAATTGCCGCTAAAGCTGCAGTTGGGAATCTGCCCTGT" +
                "TTAATATTTCAGTAGAGTGGTATTTGCTTAGCCCAAAAACCATGTTGTCAATTACAAAAA" +
                "TGCTTTATGTGAGACTGGGGCCACACTAATAAGTATTGAGCATCTTTTAAATGCTGTGGC" +
                "ACCGTGAGAGATGCAGAACGAAATCACTACCCACAGAGCTTTTGCAGGTTAGTTGAATTT" +
                "AGGTATTATGCAAAATTTCTGAAACCAGACTTCTCATCATCCTTTTTTTTTTAAACAATT" +
                "TCCTCTCTCTGCTTTGCCCTGTCTCCTCACCCACCCACACCATTCCAATCAGTTGGCAAG" +
                "AGCCCAGATGTGTAATTTTCCATATATCCTTTTTGTGAAGACATTGCTAATGCTGGGTTT" +
                "TGTTTTTTGTTTTTTGGTTTTTTTAATCTTTTGAAGTGATTAGAAAAGTTTATTTTGTGC" +
                "TTAGGATATTTTTCTAAGGCATCACAGGTTACACATCCAAACTCTTCAATGGTATAATAT" +
                "TTTATATTCTAAAGGAGAGACCTTTAAAGAAAACTTGTACATTATGCTACTATAAGTCTA" +
                "GTGGATTCTCCTATCCGCAGAGCCTAGAAAGAAGGGGACATTACAGAAATTGTCTACTAC" +
                "ATAATGGTCAGTTGATTCATTGTATTTATGGTTTTCCCCCTTCTTGTAAGGTGAAAACTA" +
                "TGTATGCCCTTTAAGGAGTATGCTCTTTAAGGAGTAAAAATACACTAAGTGTACCATCCT" +
                "GTTGATTTCTACCTGTAAGATACCACACAATATTAGCAGTTAGGAAAGAACAGGAAAATA" +
                "TGAAGTTTGTATCTTAAAATATAAAAATGTGtggcgaaaccccatctctactaaaaatac" +
                "aaaaattagccgggtatagtggcgtgcacctatagtcccagctacttgggaggctgaggc" +
                "agaagaatcacttgaatccgggaggcagaggttgcagtgagctgaggtcatgccactgca" +
                "ctccagcctgggtgacagagcgcgactccatctcaaaaaaTAATGataataataaatata" +
                "tatatatataGTTAATGATTTTGAAACATCAAGCATTACAGACTGTAAAATTAATTAAGA" +
                "ACTTTCTGTATATGATGCCAAAGATACATTTAAAACATATACAAGAAGATGCTTTTTCCT" +
                "GAGTAGAATGCAAACTTTGTTTTATATTAACCTTCTGTGAATTTTCAAAATGTAAAATAC" +
                "CAGGACTTTTCCACATCAGACAAAAATCAGGAATGTTCACCTTCACATCCAAAAAGAAAA" +
                "ATTTTAAAAGACAATTTCAAGTAGTTCAGCAAGAATGATTTAAAATCTGAAATGAATGGC" +
                "CAAAATTTTAAATTATCAACAGACAGTTCAATTTGATGGATCTCTCAGTAAACTTCAGTT" +
                "TGAAACAACAACAAAAAATGCTGTTTACTAAATCATAAAAGATAATTCCAGGATATTATC" +
                "CAATTTGAAAAATAAAAAATGTAACCCGTAATAAATAAGAAAAATACAAGAGAAAATCAA" +
                "CCTTTATTGGAATCGAGAGAATACCATGGACTTTAAAACTTCCTAAATCAGTAGCTTATC" +
                "CTATATTACCATGTGTAGAAAACTGCAACTAATTAATGTAAGGTAGTTTTTATTAGTTGC" +
                "ATAACTTAAAAATATGAGGAAATTTTGGAATATATCTCTAAAACCACGGAATTGTCACTG" +
                "AAATATATATTTCTTGAGACAGTGGGCAAAGTTCCCATTTATGGGAAATACTTTCCTTTT" +
                "TTCACACACATGAAACTGAGAAAAATTATATCAAATGAGAAATATTTTTCTCTAAAATAA" +
                "TCTTAAGTACCCCAATAATGCAATACTGGGGAAATGTAAATTTTCAAAACTCAGATTTGA" +
                "AACAGGTTATTATTAAACAAATATACATAAATCTTATTGTTTGGCAAGATTTTTCAAAAA" +
                "TTAGAGAACTAGTTAAACCACCATACTGTCCTTAAATCATATTTCAAACTTACATACCTA" +
                "GTGCTTTTATGTTCTGAATGTAGAGTCTTCAATTTAATGACAATCTAGACTGAATGCTGT" +
                "AATATACAAGCAAGTCACAGTTCACTTCAAACCAAAAGAAATAATCAGTCTTCTGTTTTT" +
                "ATCAAAATCATGATATTAAGATAACTATACAATTTATCTGTGACCAGTGATGGACCCAGA" +
                "GAGTGTTGTGTTATGGCATTCTGTGGAAAGTCTTTGTTCCTTCTTTACTTTTGGCTTCTT" +
                "CTTCTGAAACATCTTCTTTATCCGCCTCTTGTTCTTCCTCCAGTTTTTTCAAAGGTTGAG" +
                "CAGATTCTGATAATTTTTTTGAAGGGTATGGCTGTGGTGTGTGCCTTTCTGAAGGACAAA" +
                "GGCAACCTGCCACAAATATCATACAGAGTCCTAGTAACAGTCCAGAATGCAGAGTTGCTA" +
                "AAGGAAAAACAGCATATGATCCCCACACTGGCAATCCAATGTCTTCAATAAAGTAGTTAT" +
                "GGCAAGTCCTGATCCACGTAGATAGCTGAAAGAGTGCTGACGTACTACTCATCTGAACAG" +
                "AACCTGAAACAAACCATGATGAAACGGGTTCAATACTCTTCCACTCTTTATCACTTATAA" +
                "AGTTTATGAAGTCCTTCTGAGTCCTTGGACCCTGAGGATGCCTAAATTCACCATCTTTAC" +
                "AATGATAAATAGTAGGAAGAACAGTTATTGTAAACTGTCCAGTCAGTCCTGGCTGCTCTG" +
                "TGACATCTACTTTCACAACATTAACCTCAGATCTTCTCCCCATTCAGCAAAACTTTCCCA" +
                "TTCCGGTTAATGGTTTTGACAAGCAGGGCACCACGGGGCATAAAATTGTATCATCCAGCC" +
                "TCCTTCCAGCAGCTCTCTCCAGTTCTTGTCTGTGATGATGCGTACGTTGCTCTGCCGCCT" +
                "GTGGGTCCAGGGAGCACCCCCAAGCAACAGTACCAGGACTGCCAGCGGAACTGCAAGACT" +
                "CCTGGAGGGTGCCATGTCTGCCGCTTGCCCACCTCACAGCAAGCGTGGCGGCCCAACACT" +
                "AGGTTTTTTAAAAACTGTGACTATCAGTGTTTTAAAAATTGCCCGGTAACTCTAGACTTC" +
                "AAAAGTGGGATAAGTAATGATAAACCAATAATAAACTTAGGAGAAGCATAGTCTGCTTTA" +
                "GTTATATTGTTATGCCATATTATGGTCAGTAACACAGTAAAGGCCTAATTCATCTGCTTT" +
                "CTAAATTGGTTCTGTACTTTTCTAGAAAAGCCTACATGTATATACTTAGTTACAGCTGCA" +
                "CTTCTCCATTACTTATTTTTAGGAAGGTTATAGAGATGGAATAGATGCTGGCAAAGCAGT" +
                "TACTCTTCAACAGGGCTTCAATCAAGGTTATAAGAAAGGTGCAGAAGTCATTTTAAACTA" +
                "TGGACGACTCCGAGGAACATTGAGGTAATTTTTAAAGTCTAAATGCTGAATCATTTTAAC" +
                "CTCAATACTACTGGAGGATGTTTCTGTATAAATAAAGTGTTTAAACTGAAATGCTTTTCC" +
                "TGGTGCTAAATACACTAAAGCGTGTCGCAGATCATAGAATTATATTGCCTTCAAAAAGTC" +
                "AAAATCTTTATCAGCTCATCTACTTTAATGTGTGAACTACATATTGTCTTTTCGTGCAAA" +
                "GAAATGGTAAGAAGATGTATACTTCTGCTACCTGAACAATTATCTATCTCATTGAAAGGT" +
                "CTTCAGATTTTGAATAAAACTTGTAGTACTTCCACACAGTATGACAGACCTCTAGACTAG" +
                "AAGTACATGATGAAAATAGTTGGTAATTAAGATAAAATTGATTTAATTTACTTTAGTCCT" +
                "GAACATTGAATACTTGTCAGGATGCCATTGCAATAATGGCATATATCGGAGCCAAATGGT" +
                "CAAATGATACACAGAGCCAGGAGCCTAGCAGCCTTGTCCAGTTTGATGCTCTATACcaag" +
                "cttgtccaaccagtggcctgcatatcacatgtggcccaggacggctttgaatatggccca" +
                "acacaaattcataaactttcttaaaacaatatgagcattatgaaatttttttcatgatat" +
                "tttttcttttttcttttttttttttttttaactcatcagctatcattagtgttaatgtat" +
                "tttatgtgtggcccaagacagttcttccaatgtggcccaggaaagccaaaagattggaca" +
                "cccctgCTTTATACCCTTTACACTGTCCTTGGTAGAGAAAAAAAAAATGCTTCAAAGAAT" +
                "CGCTAATTTTAAAGAAGAGTAGATGATAAAAGTTACCAAAACAAACCGAAAAATTTATTG" +
                "TATTTGGGATTTTAGAAAATCCAACTATTAGGAACCAGAATTTAGTCTGCTACAGTAGGA" +
                "AAACAATGTGAATATTCACATCATCAAGTTGATGTTACATAACCTTAGAAAGCTACTGCT" +
                "GAATCTTTTATATCAATGGATTCTATTTTTAAATACTTTTCATAATAATCATTATTTTAT" +
                "GACATGACTATAATATTAAATCTGTTAGGACTAGAAGAATTTTTACCTTTTTCAAGGAAA" +
                "TTGTTAGTAGTTCAGCAAACAGTTTCTACTCTGTGACATAAGCCCAGGAAAGTGAAGTCT" +
                "CTTGAAAACTTCTTTTCTCTAACCTTCATTCTTGATGGCAAGCAACTATGTGCTTAGAAC" +
                "GAtggttttcaactttggttgcaccttaactctgaaacttaaaaaaaagataccccctga" +
                "gattctgatttaattggtgtggagtataatctgggccttgataggggtcagagctcttca" +
                "ggtgattctaatgtgcatccatgattgagaattgctAGTTAAGAAGCTGTTTAATGTCCT" +
                "TAAAGAAGAAACTAATTTTTCTTTCTCGGAGTTGTATTCATCTTCAACAGATATTACATA" +
                "GTCATAAGAGAAAAATATAAAATCAGGAAAAGCGTATATAGAGTTATGAAAGAGGGGTTA" +
                "TGAATTATAAACAGTTTTATGATTAAGTCCAATCGTTTAATTGTTATTGAAAGATAGTCT" +
                "TATATTTTTAAGTCCTATTTTGCTATTTAACCCTTGTTTATACTTTTGTTCAGTGCTTTG" +
                "CTCTCCTGGTGTCACCTTCATAATAATAATTCAACTTTGATCAATAAAATAAACAATCTT" +
                "CTGGATGCAGTTGGCCAGTGTGAAGAGTATGTGCTCAAACATCTGAAATCAATCACTCCA" +
                "CCGTCCCATGTTGTAGATTTATTGGACTCCATTGAGGATATGGACCTTTGTCATGTAGTT" +
                "CCAGCTGAGAAAAAGATTGATGAAGCTAAAGATGAAAGACTCTGTGAAAATAATGCTGAG" +
                "TTTAACAAAAACTGTAGCAAGAGCCATAGTGGGATAGATTGTTCATATGTAGAATGTTGT" +
                "AGAACACAGGAGCATGCACATTCAGAAAACCCAAGCCCCACATGGATTTTGGAACAGACA" +
                "GCCAGTTTAGTTAAACAGCTGGGCCTATCAGTAGATGTATTACAACACCTCAAACAACTA" +
                "TAAAATTACCTTCCCTTTTCTAATGAAAATAATGTTCAGAACATTTGGTTTCCTAACAAT" +
                "CGAAATTTGTACTGGTTTCTGCATCAAACACCTCAACTGTAGGGTTACCCTTTATGGAAG" +
                "TTTGAAATTAACACTATTGTCTTCAAAATTAACACTATTAAATGTAATATAAGCCTTT";
    }


    private TestingData() {
        // no-op
    }
}
